packages:
  - '.'
verifyDepsBeforeRun: false
packageImportMethod: copy
minimumReleaseAge: 1440
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600
allowBuilds:
  sharp: true
  unrs-resolver: true
